### ISSUE TITLE
Export of data is failing with error below I have been able to in past, but not now.

### ISSUE THREAD

**Issue by BruceSparks** [NickHeiner/fitbit-export#11]
{
  "message": "Unexpected token < in JSON at position 0 in \"https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/max.json\": \n<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\">...",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/activityCalories/date/today/max.json",
  "statusCode": 520,
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/max.json"
}
ParseError: Unexpected token < in JSON at position 0 in "https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/max.json": 
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US">...
    at stream.catch.then.e (\\100.82.102.36\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:109:14)
    at wrappedPromise.linkTransaction (\\100.82.102.36\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.102.36\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.102.36\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by NickHeiner** [comment]
Hi! Thanks for filing this issue. You can use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) on Github to format code in a more readable way. In particular, you can use three backticks (```) to format a code block.

Can you provide any more detail about what you were doing when this happened? How long have you had your account for? Do you have a lot of data?

**Comment by BruceSparks** [comment]
Thanks for the response. This is a coding method I have no background so can't coment on formatting or looking at the code. I do have a lot of data in there. About three years I think. Just running your script from web link you provided. Thanks Bruce.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: Nick HeinerSent: Sunday, September 4, 2016 11:48 AMTo: NickHeiner/fitbit-exportReply To: NickHeiner/fitbit-exportCc: BruceSparks; AuthorSubject: Re: [NickHeiner/fitbit-export] Export of data is failing with error below I have been able to in past, but not now. (#11)Hi! Thanks for filing this issue. You can use Markdown on Github to format code in a more readable way. In particular, you can use three backticks (```) to format a code block.

Can you provide any more detail about what you were doing when this happened? How long have you had your account for? Do you have a lot of data? 

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NickHeiner/fitbit-export","title":"NickHeiner/fitbit-export","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NickHeiner/fitbit-export"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NickHeiner in #11: Hi! Thanks for filing this issue. You can use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) on Github to format code in a more readable way. In particular, you can use three backticks (```) to format a code block.\r\n\r\nCan you provide any more detail about what you were doing when this happened? How long have you had your account for? Do you have a lot of data? "}],"action":{"name":"View Issue","url":"https://github.com/NickHeiner/fitbit-export/issues/11#issuecomment-244610842"}}}

**Comment by NickHeiner** [comment]
I've followed up with Fitbit to learn about what this error means: https://github.com/NickHeiner/fitbit-export/issues/11.

**Comment by BruceSparks** [comment]
Thank you.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: Nick HeinerSent: Sunday, September 4, 2016 12:32 PMTo: NickHeiner/fitbit-exportReply To: NickHeiner/fitbit-exportCc: BruceSparks; AuthorSubject: Re: [NickHeiner/fitbit-export] Export of data is failing with error below I have been able to in past, but not now. (#11)I've followed up with Fitbit to learn about what this error means: #11.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NickHeiner/fitbit-export","title":"NickHeiner/fitbit-export","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NickHeiner/fitbit-export"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NickHeiner in #11: I've followed up with Fitbit to learn about what this error means: https://github.com/NickHeiner/fitbit-export/issues/11."}],"action":{"name":"View Issue","url":"https://github.com/NickHeiner/fitbit-export/issues/11#issuecomment-244613228"}}}

**Comment by NickHeiner** [comment]
Hey Bruce – try this again. I've removed the troublesome endpoint in 9d2398b72abc11d96d54b867b7f46a6a288395b7.
