### ISSUE TITLE
Export your historical Fitbit data for free

### ISSUE THREAD

**Issue by ingfcuenca** [NickHeiner/fitbit-export#15]
If you can code, you're welcome to send me a pull request on GitHub.

I am new swift developer still learning and I would like to get the food log data to import into my glucose app, thus I would like to send you a pull request, it would be great if I can get that food log data in a CVS file or JSON format, therefore I can somehow import it into my app periodically.

thank you in advance

Edison

**Comment by NickHeiner** [comment]
This app uses JavaScript and NodeJS, so you'd have to learn that to send a PR. But I'm happy to review something that you send me. :smile:
