### ISSUE TITLE
HTTPError: Response code 422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by Winkster** [NickHeiner/fitbit-export#26]
**It would seem that this app does not work at all, unfortunately, as anyone clicking the "download all data..." button seems to get this error every single time.** Also pls know I was definitely logged in to the app via FitBit OAuth as my FitBit avatar was clearly visible in the upper right hand corner of the offending page.  Thanks.

--------------------------------------------------

Fitbit Data Export
Oops! Something broke.

Here's the error:

{
  "message": "Response code 422 (Unprocessable Entity)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesSedentary/date/today/max.json",
  "statusCode": 422,
  "statusMessage": "Unprocessable Entity",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesSedentary/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"validation\",\"fieldName\":\"Request\",\"message\":\"The number of data points queried exceeds limit.\"}]}"
}

HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.e (D:\home\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedHandler (D:\home\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:201:48)
    at process._tickCallback (internal/process/next_tick.js:109:7)

To report this, file an issue on GitHub. Please paste this full error, and provide a detailed description of what you were doing. Thanks!

**Comment by NickHeiner** [comment]
Yes, I agree that this app is broken for everyone right now. Unfortunately, I don't have the time to fix it at the moment, but pull requests are always welcome! :smile:

**Comment by Fragrancer** [comment]
Any luck fixing the export? Thanks.

**Comment by NickHeiner** [comment]
Fitbit now has a complete export on their site. I'll be decommissioning this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!

**Comment by Fragrancer** [comment]
You can export data only for 31 days, not all data. 
Do you know any other service where you can download all data from Fitbit? 

Thanks.

**Comment by NickHeiner** [comment]
![image](https://user-images.githubusercontent.com/829827/52180421-a351ba80-279a-11e9-8abe-d9ea9c3b9243.png)

You need to click the link to use the new export tool. That'll have full data. I did it myself and verified that all the data was there.

If you don't see that link for the new tool, then it means that Fitbit is rolling out the update incrementally and hasn't enabled it for you yet. You'll see it eventually.
