### ISSUE TITLE
"Internal Service Error" when logging in

### ISSUE THREAD

**Issue by Amyunimus** [NickHeiner/fitbit-export#9]
I'm getting an "Internal Service Error" displaying on an otherwise blank page when I've clicked both "Get started" and "Log in w/ Fitbit". It's been there for a  few days.

**Comment by NickHeiner** [comment]
This is happening because Fitbit removed support for the authentication mechanism the app currently uses. I'll try to find time soon to upgrade to the new supported mechanism.

**Comment by e1red** [comment]
came to visit to say so.  good to see it's already in the works.

**Comment by NickHeiner** [comment]
This should now be fixed! Please comment here if you're still experiencing this issue.

**Comment by NickHeiner** [comment]
Fixed via 258b461fdcfe623242f298e78b120bfc21f98199.
